//  Rest API Ag360Api
//  Version 1.0 (Lyes Hamrani)
//  Plug-IN : vscode-restclient (Huachao)
//  https://github.com/Huachao/vscode-restclient

@hostname = localhost

@port = 3001

@host = {{hostname}}:{{port}}

@contentType = application/json

GET  http://{{host}}/



