@hostname = localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json

### Route par défaut de l'API
GET  http://{{host}}/

### Requête d'inscription
POST http://{{host}}/users/register
Content-Type: {{contentType}}

{
  "first_name": "Quentin",
  "last_name": "Lecourt", 
  "address": "123 Main St",
  "city": "Anytown", 
  "state": "CA",
  "zip": "12345",
  "email": "quentin@cegeprdl.ca",
  "password": "Patate123",
  "type": "user"
}

### Requête de connexion
POST http://{{host}}/users/login
Content-Type: {{contentType}}

{
  "email": "test@example.com",
  "password": "test"
}
