name: Deploy API to VPS

on:
  push:
    branches:
      - Préprod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no deploy_schluter@51.222.29.128 '
            cd /var/www/shluter-systems-api &&
            git pull &&
            npm install --production &&
            pm2 restart all
          '
